apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: rbac-sa-namespace
  template: rbac-sa-namespace-template
metadata:
  name: rbac-sa-namespace
  namespace: openshift
objects:

#Create user for UI
- apiVersion: user.openshift.io/v1
  groups: null
  identities:
  - anypassword:${USER_NAME}
  kind: User
  metadata:
    name: ${USER_NAME}

#Add clusterrole "registry-controller" to user 
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: registry-controller
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${USER_NAME}

#Create Project "jenkins-ci"
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ""
      openshift.io/display-name: ""
    name: ${JENKINS_PROJECT_NAME}
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active

#Create ServiceAccount
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${JENKINS_SERVICE_NAME}"}}'
    name: ${JENKINS_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}

#Add role to SA
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: edit
    namespace: ${JENKINS_PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${JENKINS_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}

#Create Project Thunder
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ""
      openshift.io/display-name: ""
    name: ${THUNDER_PROJECT_NAME}
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active

# Allow pull image from project "jenkins-ci" to "thunder"
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: system:image-puller
    namespace: ${JENKINS_PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
    namespace: ${JENKINS_PROJECT_NAME}
  subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${THUNDER_PROJECT_NAME}

# #Allow containers to run as root
# - apiVersion: security.openshift.io/v1
#   kind: SecurityContextConstraints
#   metadata:
#     name: anyuid
#   volumes:
#   - configMap
#   - downwardAPI
#   - emptyDir
#   - persistentVolumeClaim
#   - projected
#   - secret
#   priority: 10
#   readOnlyRootFilesystem: false
#   requiredDropCapabilities:
#   - MKNOD
#   runAsUser:
#     type: RunAsAny
#   seLinuxContext:
#     type: MustRunAs
#   supplementalGroups:
#     type: RunAsAny
#   users:
#   - system:serviceaccount:${THUNDER_PROJECT_NAME}:default
#   allowHostDirVolumePlugin: false
#   allowHostIPC: false
#   allowHostNetwork: false
#   allowHostPID: false
#   allowHostPorts: false
#   allowPrivilegeEscalation: true
#   allowPrivilegedContainer: false
#   allowedCapabilities: null
#   defaultAddCapabilities: null
#   fsGroup:
#     type: RunAsAny
#   groups:
#   - system:cluster-admins

parameters:
- description: User Name.
  displayName: User Name
  name: USER_NAME
  value: openshift-demo
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: jenkins
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: JENKINS_PROJECT_NAME
  value: "jenkins-ci"
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: THUNDER_PROJECT_NAME
  value: "thunder"