apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: thunder-build
  template: thunder-build-template
metadata:
  name: thunder-build
  namespace: openshift
objects:

-
  apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: thunder-alpine
    namespace: ${NAMESPACE}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: thunder_alpine:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /nginx_phpfpm
      git:
        ref: alpine_build
        uri: https://github.com/ros-kamach/thunder_nginx_phpfpm
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: alpine_baseimage:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: eRWXyQKLJT9qXSZzWdNB
      type: GitHub
    - generic:
        secret: aNSpMKtoDrqplwXCFnw4
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: roskamach/alpine_baseimage@sha256:08b8dd5865d5aeabdaf8822cae30a7bcaedcabd2837a3cb75233ea1f9dddb945
      type: ImageChange

- 
  apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: alpine_baseimage
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: roskamach/alpine_baseimage:latest
      from:
        kind: DockerImage
        name: roskamach/alpine_baseimage:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

-
  apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: thunder_alpine
    namespace: ${NAMESPACE}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: docker-registry.default.svc/${NAMESPACE}/thunder_alpine

parameters:
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: NAMESPACE
  value: "jenkins-ci"