apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: thunder-pipeline
  template: pipeline-template
metadata:
  name: thunder-pipeline
  namespace: openshift
objects:

#Pipeline Build on GitHub chainge (Thunder)
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: thunder-build-pipeline
      name: thunder-build-pipeline
    name: thunder-build-pipeline
    namespace: ${JENKINS_PROJECT_NAME}
  spec:
    runPolicy: Serial
    source:
      contextDir: nginx_phpfpm/pipeline_build
      git:
        ref: alpine_build
        uri: 'https://github.com/ros-kamach/thunder_nginx_phpfpm.git'
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PS_GIT_URI
            value: 'https://github.com/ros-kamach/thunder_nginx_phpfpm.git'
          - name: PS_GIT_REF
            value: alpine_build
          - name: JENKINS_PROJECT_NAME
            value: ${JENKINS_PROJECT_NAME}
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline

# Create Pipeline build-deploy
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: thunder-deploy-pipeline
      name: thunder-deploy-pipeline
    name: thunder-deploy-pipeline
    namespace: ${JENKINS_PROJECT_NAME}
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: nginx_phpfpm/pipeline_deploy
      git:
        ref: alpine_build
        uri: https://github.com/ros-kamach/thunder_nginx_phpfpm
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: JENKINS_PROJECT_NAME
            value: ${JENKINS_PROJECT_NAME}
          - name: THUNDER_PROJECT_NAME
            value: ${THUNDER_PROJECT_NAME}
          - name: THUNDER_HOST_NAME
            value: thunder-service.thunder.svc
          - name: SCRIPT_LINK
            value: https://raw.githubusercontent.com/ros-kamach/bash_healthcheck/master/health_check.sh 
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline

parameters:
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: JENKINS_PROJECT_NAME
  # value: "jenkins-ci"
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: THUNDER_PROJECT_NAME
  # value: "thunder"
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: jenkins