apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: jenkins-persistent
  template: jenkins-persistent-template
metadata:
  name: jenkins-persistent
  namespace: openshift
objects:

#Add role to SA for deploy jenkins in project
- apiVersion: authorization.openshift.io/v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: system:deployers
    namespace: ${JENKINS_PROJECT_NAME}
  roleRef:
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: ${JENKINS_PROJECT_NAME}
  userNames:
  - system:serviceaccount:${JENKINS_PROJECT_NAME}:deployer

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${JENKINS_SERVICE_NAME}"}}'
    name: ${JENKINS_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}


- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    name: ${JENKINS_SERVICE_NAME}_edit
    namespace: ${JENKINS_PROJECT_NAME}
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: ${JENKINS_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}

#Import image from axternal repo to lockal
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: jenkins-2-centos7-local
    namespace: ${JENKINS_PROJECT_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ${JENKINS_PROJECT_NAME}/jenkins-2-centos7-local:latest
      from:
        kind: DockerImage
        name: openshift/jenkins-2-centos7:v3.11
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

#Make route to Service Jenkins WEB
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 5m
      template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    name: ${JENKINS_SERVICE_NAME}
    namespace:  ${JENKINS_PROJECT_NAME}
  spec:
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${JENKINS_SERVICE_NAME}

# Create Persistent Volume Claim
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pvc-${JENKINS_SERVICE_NAME}-storage
    namespace: ${JENKINS_PROJECT_NAME}
  spec:
    accessModes:
      - ${STORAGE_ACCSESS_MODE}
    resources:
      requests:
        storage: ${JENKINS_STORAGE_SIZE}

#Jenkins Deployment
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${JENKINS_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}    
  spec:
    replicas: 1
    selector:
      name: ${JENKINS_SERVICE_NAME}
    strategy:
      recreateParams:
        timeoutSeconds: 2400
      type: Recreate
    template:
      metadata:
        labels:
          name: ${JENKINS_SERVICE_NAME}
      spec:
        containers:
        - capabilities: {}
          env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: ${ENABLE_OAUTH}
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          # - name: DISABLE_ADMINISTRATIVE_MONITORS
          #   value: ${DISABLE_ADMINISTRATIVE_MONITORS}
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JENKINS_SERVICE_NAME
            value: ${JENKINS_SERVICE_NAME}
          - name: JNLP_SERVICE_NAME
            value: ${JNLP_SERVICE_NAME}
          # - name: INSTALL_PLUGINS
          #   value: ${PLUGINS_LIST}
          image: ${JENKINS_PROJECT_NAME}/${JENKINS_IMAGE_STREAM_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 1200
            periodSeconds: 10
            timeoutSeconds: 240
          name: jenkins
          readinessProbe:
            # failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 900
            periodSeconds: 10
            timeoutSeconds: 240
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${GUARANT_CPU}
              memory: ${GUARANT_MEMORY}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
            - mountPath: /var/lib/jenkins
              name: ${JENKINS_SERVICE_NAME}-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccountName: ${JENKINS_SERVICE_NAME}
        volumes:
          - name: ${JENKINS_SERVICE_NAME}-data
            persistentVolumeClaim:
              claimName: pvc-${JENKINS_SERVICE_NAME}-storage
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: ${JENKINS_IMAGE_STREAM_TAG}
          namespace: ${JENKINS_PROJECT_NAME}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange

#Create Service for Jenkins API
- apiVersion: v1
  kind: Service
  metadata:
    name: ${JNLP_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}
  spec:
    ports:
    - name: agent
      nodePort: 0
      port: 50000
      protocol: TCP
      targetPort: 50000
    selector:
      name: ${JENKINS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP

#Create Service for Jenkins WEB
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "${JNLP_SERVICE_NAME}",
        "namespace": "", "kind": "Service"}]'
      service.openshift.io/infrastructure: "true"
    name: ${JENKINS_SERVICE_NAME}
    namespace: ${JENKINS_PROJECT_NAME}
  spec:
    ports:
    - name: web
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${JENKINS_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP

#Variables
parameters:
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: JENKINS_PROJECT_NAME
  # value: "jenkins-ci"
- description: Project (Namespace)
  displayName: Project (Namespace)
  name: THUNDER_PROJECT_NAME
  # value: "thunder"
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: jenkins
- description: The minimum amount of CPU the container is guaranteed.
  displayName: CPU Gauraneed
  name: GUARANT_CPU
  value: 500m
- description: The maximum amount of CPU the container is allowed to use when running.
  displayName: CPU Limit
  name: CPU_LIMIT
  value: '1'
- description: The maximum amount of memory the container is allowed to use when running.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  value: 2Gi
- description: The minimum amount of memory the container is guaranteed.
  displayName: Memory Gauraneed
  name: GUARANT_MEMORY
  value: 1Gi
- description: Jenkins Storage type.
  displayName: Jenkins Starage
  name: STORAGE_ACCSESS_MODE
  value: "ReadWriteOnce"
- description: Jenkins Storage type.
  displayName: Jenkins Starage
  name: JENKINS_STORAGE_SIZE
  value: "10Gi"
- description: Name of the ImageStreamTag to be used for the Jenkins image.
  displayName: Jenkins ImageStreamTag
  name: JENKINS_IMAGE_STREAM_TAG
  value: jenkins-2-centos7-local:latest
- description: The name of the service used for master/slave communication.
  displayName: Jenkins JNLP Service Name
  name: JNLP_SERVICE_NAME
  value: jenkins-jnlp
- description: Whether to enable OAuth OpenShift integration. If false, the static
    account 'admin' will be initialized with the password 'password'.
  displayName: Enable OAuth in Jenkins
  name: ENABLE_OAUTH
  value: "true"
- description: Whether to perform memory intensive, possibly slow, synchronization
    with the Jenkins Update Center on start.  If true, the Jenkins core update monitor
    and site warnings monitor are disabled.
  displayName: Disable memory intensive administrative monitors
  name: DISABLE_ADMINISTRATIVE_MONITORS
  value: "false"
- description: Jenkins Plugins to install
  name: PLUGINS_LIST
  value: >-
          locale
          saferestart
          authorize-project
          ant
          pam-auth
          blueocean-autofavorite
          cloudbees-bitbucket-branch-source
          blueocean-bitbucket-pipeline
          blueocean
          blueocean-core-js
          blueocean-pipeline-editor
          bouncycastle-api
          branch-api
          blueocean-commons
          conditional-buildstep
          blueocean-config
          config-file-provider
          credentials
          credentials-binding
          blueocean-dashboard
          jenkins-design-language
          display-url-api
          blueocean-display-url
          docker-commons
          docker-workflow
          durable-task
          blueocean-events
          external-monitor-job
          favorite
          cloudbees-folder
          git
          git-client
          blueocean-git-pipeline
          git-server
          github
          github-api
          github-branch-source
          blueocean-github-pipeline
          handy-uri-templates-2-api
          htmlpublisher
          blueocean-i18n
          jackson2-api
          javadoc
          ace-editor
          handlebars
          momentjs
          jaxb
          jira
          blueocean-jira
          job-dsl
          jsch
          junit
          blueocean-jwt
          kubernetes
          kubernetes-credentials
          ldap
          mailer
          matrix-auth
          mercurial
          jdk-tool
          antisamy-markup-formatter
          blueocean-personalization
          pipeline-graph-analysis
          blueocean-pipeline-api-impl
          blueocean-pipeline-scm-api
          pipeline-utility-steps
          workflow-api
          workflow-basic-steps
          pipeline-build-step
          pipeline-model-definition
          pipeline-model-extensions
          workflow-cps
          pipeline-input-step
          workflow-job
          pipeline-model-api
          workflow-multibranch
          workflow-durable-task-step
          pipeline-rest-api
          command-launcher
          maven-plugin
          workflow-scm-step
          pipeline-stage-view
          run-condition
          subversion
          windows-slaves
          apache-httpcomponents-client-4-api
          script-security
          ssh-credentials
          openshift-deployer